### ISSUE TITLE
Breaking JSOX.cc into multiple files

### ISSUE THREAD

**Issue by aminya** [d3x0r/jsox-wasm#2]
This file is very big, and GitHub cannot show it properly
https://github.com/d3x0r/jsox-wasm/blob/master/jsox.cc

**Comment by d3x0r** [comment]
It started as individual files... 
The list of files is here
https://github.com/d3x0r/jsox-wasm/blob/master/mk.bat
Paths are all relative to this repo https://github.com/d3x0r/sack

**Comment by d3x0r** [comment]
https://github.com/d3x0r/jsox-wasm/issues/1#issuecomment-629699517
